#ifndef PLAYER_REGISTER_TYPES_H
#define PLAYER_REGISTER_TYPES_H

#ifndef EATER_REGISTER_TYPES_H
#define EATER_REGISTER_TYPES_H

#ifndef EATEREAT_REGISTER_TYPES_H
#define EATEREAT_REGISTER_TYPES_H

#ifndef EATERCHASE_REGISTER_TYPES_H
#define EATERCHASE_REGISTER_TYPES_H

#ifndef EATERRETREAT_REGISTER_TYPES_H
#define EATERRETREAT_REGISTER_TYPES_H

#ifndef ATTACKER_REGISTER_TYPES_H
#define ATTACKER_REGISTER_TYPES_H

#ifndef ATTACKERATTACK_REGISTER_TYPES_H
#define ATTACKERATTACK_REGISTER_TYPES_H

#ifndef ATTACKERCHASE_REGISTER_TYPES_H
#define ATTACKERCHASE_REGISTER_TYPES_H

#ifndef ATTACKERDODGE_REGISTER_TYPES_H
#define ATTACKERDODGE_REGISTER_TYPES_H

#ifndef CACTUS_REGISTER_TYPES_H
#define CACTUS_REGISTER_TYPES_H

#ifndef FOOD_REGISTER_TYPES_H
#define FOOD_REGISTER_TYPES_H

#ifndef CAMERA_REGISTER_TYPES_H
#define CAMERA_REGISTER_TYPES_H

#ifndef RAYCAST_REGISTER_TYPES_H
#define RAYCAST_REGISTER_TYPES_H

#ifndef GROUND_REGISTER_TYPES_H
#define GROUND_REGISTER_TYPES_H

#ifndef WALL_REGISTER_TYPES_H
#define WALL_REGISTER_TYPES_H

#ifndef FINITESTATEMACHINE_REGISTER_TYPES_H
#define FINITESTATEMACHINE_REGISTER_TYPES_H

#ifndef STATE_REGISTER_TYPES_H
#define STATE_REGISTER_TYPES_H

void initialize_player_module();
void uninitialize_player_module();

#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
